"""Install-time hook that bakes the git SHA + build time into the package.

``pyproject.toml`` remains the source of truth for project metadata. This file
exists only to override ``build_py`` and ``develop`` so that every invocation
of ``pip install`` / ``pip install -e .`` writes a fresh ``config/_build_info.py``
with the current commit's SHA and the UTC build time. At runtime,
``config.version`` reads those values so exports can be traced back to the
exact build regardless of whether the ``.git`` directory is shipped with the
deployed artifact.

``config/_build_info.py`` is listed in ``.gitignore`` — it's a per-install
artifact, not source.
"""

from __future__ import annotations

import subprocess
from datetime import datetime, timezone
from pathlib import Path

from setuptools import setup
from setuptools.command.build_py import build_py
from setuptools.command.develop import develop


def _resolve_sha(root: Path) -> str:
    """Return the full git SHA for ``root`` or ``'unknown'`` if git is absent."""
    try:
        result = subprocess.run(
            ["git", "-C", str(root), "rev-parse", "HEAD"],
            capture_output=True,
            text=True,
            timeout=5,
        )
        if result.returncode == 0:
            sha = result.stdout.strip()
            if sha:
                return sha
    except Exception:
        pass
    return "unknown"


def _write_build_info() -> None:
    root = Path(__file__).resolve().parent
    target = root / "config" / "_build_info.py"
    target.parent.mkdir(parents=True, exist_ok=True)

    sha = _resolve_sha(root)
    build_time = (
        datetime.now(timezone.utc).isoformat(timespec="seconds").replace("+00:00", "Z")
    )

    target.write_text(
        "# Auto-generated by setup.py — do not edit.\n"
        "# Written at `pip install` time so that deployed artifacts can report\n"
        "# their provenance even when `.git` is unavailable.\n"
        f'BUILD_SHA = "{sha}"\n'
        f'BUILD_TIME = "{build_time}"\n',
        encoding="utf-8",
    )


class BuildPyWithStamp(build_py):
    """``python -m build`` / ``pip install`` path."""

    def run(self) -> None:
        _write_build_info()
        super().run()


class DevelopWithStamp(develop):
    """``pip install -e .`` path."""

    def run(self) -> None:
        _write_build_info()
        super().run()


setup(cmdclass={"build_py": BuildPyWithStamp, "develop": DevelopWithStamp})
